# Generated by Django 3.1.7 on 2021-03-26 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hue',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
