# Generated by Django 3.1.7 on 2021-03-27 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210326_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hue',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
