# Generated by Django 3.1.7 on 2021-03-27 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210327_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('https:\\/\\/i.imgur.com\\/\\w*.(png|jpg|gif|jpeg)')]),
        ),
    ]
